# ----------------------------------------------------
# 1. ConfigMap (DB URL)
# ----------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb

---
# ----------------------------------------------------
# 2. Secret (DB username + password)
#   username: spring
#   password: spring123
# ----------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==        # spring
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz    # spring123

---
# ----------------------------------------------------
# 3. Spring Boot Deployment
#   IMAGE IS REPLACED BY JENKINS (sed)
# ----------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: <docker-image> 
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret

---
# ----------------------------------------------------
# 4. Service (NodePort)
#   Access: http://<node-ip>:30080
# ----------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-app
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
  type: NodePort
